### ISSUE TITLE
Error if old puppet-doc format is found

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/puppet-lint-param-docs#24]

**Comment by alexjfisher** [comment]
Sounds reasonable and something that I'd been thinking about.  Possibly this could be covered by a configuration option for specifying allowed documentation styles?  I know The Foreman project would like to be able to enforce puppet-strings style in some repos, and rdoc in others.
Maybe even an autofix option that would convert the docs??

**Comment by ekohl** [comment]
I would certainly like a config option for valid styles and it'd be fine to default to puppet-strings. As long as I can still indicate that rdoc is valid.
